// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables or fallback to demo values
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://rvlszwechlzgfbswwlnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2bHN6d2VjaGx6Z2Zic3d3bG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzAwNjUsImV4cCI6MjA2NDQ0NjA2NX0.5X0iSaGIq0haDnnR7cE-letveR04cESlheC-BqdkPxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});